version: "3"
services:
  app:
    image: syncthing/syncthing
    restart: unless-stopped
    hostname: ${SYNCTHING_HOSTNAME:-syncthing}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./_:/var/syncthing
      - /media/backup:/var/syncthing/backup
      - /media/windree:/var/syncthing/windree
      - /media/me:/var/syncthing/me
    network_mode: host
    