version: "3"
services:
  app:
    image: syncthing/syncthing
    restart: unless-stopped
    hostname: ${SYNCTHING_HOSTNAME:-syncthing}
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./_:/var/syncthing
      - /media/marble:/var/syncthing/marble
    network_mode: host
    