services:
  app:
    image: syncthing/syncthing
    restart: unless-stopped
    hostname: ${SYNCTHING_HOSTNAME:-syncthing}
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./data:/var/syncthing
      - ${SYNCTHING_PATH}:/data
    network_mode: host
    
